/* Troubleshoot content (Jenny's sourced research, /workspace/dt-research/troubleshoot.json).
 * Generated by Maria for the Troubleshoot cards. ids = <symptom>-<n> in research order; DT_CALC.troubleChecks uses these ids. */
(function(){ window.DT_DATA = window.DT_DATA || {}; window.DT_DATA.TROUBLE = {
 "broke": [
  {
   "id": "broke-1",
   "title": "Tap drill too small, so % thread is too high",
   "fix": "Use the largest drill the thread class allows. Torque climbs steeply as % thread rises.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319427/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Tap_-_Vol_1_-_IA.pdf"
   }
  },
  {
   "id": "broke-2",
   "title": "Tap hits the bottom of a blind hole",
   "fix": "Drill deeper or shorten the thread. Haas: drill at least .050\" deeper than the tap goes.",
   "src": {
    "name": "Haas Automation",
    "url": "https://www.haascnc.com/service/troubleshooting-and-how-to/troubleshooting/tap-breakage-troubleshooting.html"
   }
  },
  {
   "id": "broke-3",
   "title": "Thread engagement deeper than 1.5 x tap diameter",
   "fix": "Keep thread length near 1.5xD. Deeper adds no strength, and breakage risk rises sharply.",
   "src": {
    "name": "Haas Automation",
    "url": "https://www.haascnc.com/service/troubleshooting-and-how-to/troubleshooting/tap-breakage-troubleshooting.html"
   }
  },
  {
   "id": "broke-4",
   "title": "Chips packing in the flutes or at the hole bottom",
   "fix": "Spiral flute for blind holes, spiral point for through holes. Spiral points pack chips in blind holes.",
   "src": {
    "name": "Haas Automation",
    "url": "https://www.haascnc.com/service/troubleshooting-and-how-to/troubleshooting/tap-breakage-troubleshooting.html"
   }
  },
  {
   "id": "broke-5",
   "title": "Tap speed above the published range",
   "fix": "Lower the cutting speed to the tap maker's recommendation.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/troubleshooting-tapping"
   }
  },
  {
   "id": "broke-6",
   "title": "Runout, or tap not lined up with the drilled hole",
   "fix": "Check tap TIR; some taps break past .001\" (.03 mm). Use a positive-drive tap collet.",
   "src": {
    "name": "Haas Automation",
    "url": "https://www.haascnc.com/service/troubleshooting-and-how-to/troubleshooting/tap-breakage-troubleshooting.html"
   }
  },
  {
   "id": "broke-7",
   "title": "No torque protection when torque spikes",
   "fix": "Use a tap holder with torque adjustment or a torque-limiting feature.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319427/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Tap_-_Vol_1_-_IA.pdf"
   }
  },
  {
   "id": "broke-8",
   "title": "Tap type or coating wrong for the material",
   "fix": "Pick a tap made for the material. Harder work needs a more wear-resistant tap or coating.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/troubleshooting-tapping"
   }
  }
 ],
 "oversize": [
  {
   "id": "oversize-1",
   "title": "Rigid-tap feed doesn't equal RPM x lead",
   "fix": "G94: F = RPM x lead per minute. G95: F = lead. If F was rounded, use G95.",
   "src": {
    "name": "Fanuc 30i-A manual p.78",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "oversize-2",
   "title": "Tension/compression holder on a synchronized machine",
   "fix": "Use a rigid or minimal-compensation synchro holder. Float lets spiral flutes pull in and overcut.",
   "src": {
    "name": "OSG",
    "url": "https://www.mscdirect.com/knowledge-center/articles/video-60sec-troubleshooting-threading-tension-compression-vs-rigid-tapping"
   }
  },
  {
   "id": "oversize-3",
   "title": "Tap tolerance (H-limit) too big for the thread class",
   "fix": "Choose a tap with a lower tolerance; check the tap's markings against the class needed.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/troubleshooting-tapping"
   }
  },
  {
   "id": "oversize-4",
   "title": "Chips packing in the flutes",
   "fix": "Use spiral point or spiral flute taps, fewer flutes, or a larger hole.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "oversize-5",
   "title": "Galling: metal welding onto the tap flanks",
   "fix": "Use a surface-treated tap, better lubricant, and a lower tapping speed.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "oversize-6",
   "title": "Misalignment from a loose spindle or worn holder",
   "fix": "Correct tap-to-hole alignment and replace a worn holder.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "oversize-7",
   "title": "Spindle and Z axis drifting out of sync",
   "fix": "Check Fanuc rigid-tap sync diagnostics 455-457. A minimal-compensation holder absorbs small sync errors.",
   "src": {
    "name": "Fanuc 16i-B manual p.1134",
    "url": "https://www.drivesul.com.br/template/imagens/manuais/manuais-fanuc/fanuc-series-16i-18i-21i-model-b/Series%2016i-18i-21i-MODEL%20B%20-%20Connection%20Manual%20(Function).pdf#page=1162"
   }
  },
  {
   "id": "oversize-8",
   "title": "Minor diameter over class max (drill too big)",
   "fix": "Use a smaller drill inside the class band. YG-1: use the minimum hole size.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  }
 ],
 "tight": [
  {
   "id": "tight-1",
   "title": "Tap worn out",
   "fix": "Replace the tap.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/troubleshooting-tapping"
   }
  },
  {
   "id": "tight-2",
   "title": "Tap drill too small; material closes in after tapping",
   "fix": "Increase the drill diameter, or choose a tap with a higher tolerance.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/troubleshooting-tapping"
   }
  },
  {
   "id": "tight-3",
   "title": "Form tap with a pre-drill that's too small",
   "fix": "Form taps need a bigger drill. Start slightly over the calculated size and adjust by gauge. Example: a 1/4-20 form tap takes a #1 drill for 65% thread, where a cut tap takes a #7.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319427/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Tap_-_Vol_1_-_IA.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/8-unique-facts-about-thread-forming-taps/"
    }
   ]
  },
  {
   "id": "tight-4",
   "title": "Tap pitch diameter too small for the job",
   "fix": "Use an oversize tap (higher H-limit).",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "tight-5",
   "title": "Threads damaged by the tap on the way out",
   "fix": "Use the right reversing speed so the tap doesn't damage threads on exit.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "tight-6",
   "title": "Chips left in the hole",
   "fix": "Clear leftover chips before gauging, and improve chip removal.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "tight-7",
   "title": "Too much pull-off pressure from the tapping attachment",
   "fix": "Adjust the tapping attachment.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/troubleshooting-tapping"
   }
  }
 ],
 "wander": [
  {
   "id": "wander-1",
   "title": "No spot or center drill before drilling",
   "fix": "Spot first with a short, rigid NC spot drill, about 0.5-0.7 x drill diameter.",
   "src": {
    "name": "Guhring",
    "url": "https://guhring.com/media/support/Centering-And-Pilot-Drilling-Recommendations.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/choosing-spot-drill/"
    }
   ]
  },
  {
   "id": "wander-2",
   "title": "Spot angle smaller than the drill point angle",
   "fix": "Match the spot to the drill: 120 deg spot for 118 deg HSS, 142 deg for 135-140 deg carbide.",
   "src": {
    "name": "Guhring",
    "url": "https://guhring.com/media/support/Centering-And-Pilot-Drilling-Recommendations.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/choosing-spot-drill/"
    }
   ]
  },
  {
   "id": "wander-3",
   "title": "Drill runout in the holder or spindle",
   "fix": "Check runout after clamping; change the holder if needed.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319429/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Drilling-_Vol_1_-_IA.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/reducing-tool-runout/"
    }
   ]
  },
  {
   "id": "wander-4",
   "title": "Hole widens at the entrance (bellmouth)",
   "fix": "Check runout, adjust feed, shorten overhang. Pilot with a short drill before long drills.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-wear-and-troubleshooting"
   }
  },
  {
   "id": "wander-5",
   "title": "Long drill started without a pilot hole",
   "fix": "Pilot 1-2 x D deep with a stub drill before extra-length HSS drills.",
   "src": {
    "name": "Guhring",
    "url": "https://guhring.com/media/support/Centering-And-Pilot-Drilling-Recommendations.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/choosing-the-right-pecking-cycle-approach/"
    }
   ]
  },
  {
   "id": "wander-6",
   "title": "Angled, curved or uneven entry surface",
   "fix": "Spot or counterbore first, use a stiff stub drill, and reduce the feed. On a slope or the side of a round part, flatten the spot with a flat-bottom drill first.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319429/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Drilling-_Vol_1_-_IA.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/selecting-the-right-harvey-tool-miniature-drill/"
    }
   ]
  },
  {
   "id": "wander-7",
   "title": "Feed too high for the setup",
   "fix": "Decrease the feed, and ease the feed at entry on long or unstable drills.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-wear-and-troubleshooting"
   }
  }
 ],
 "packing": [
  {
   "id": "packing-1",
   "title": "Spiral point tap used in a blind hole",
   "fix": "Switch to a spiral flute tap. Spiral points push chips down and pack the bottom.",
   "src": {
    "name": "Haas Automation",
    "url": "https://www.haascnc.com/service/troubleshooting-and-how-to/troubleshooting/tap-breakage-troubleshooting.html"
   }
  },
  {
   "id": "packing-2",
   "title": "Straight-flute tap in long-chipping material",
   "fix": "Use spiral flute (blind) or spiral point (through). Straight flutes suit short-chipping materials.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319427/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Tap_-_Vol_1_-_IA.pdf"
   }
  },
  {
   "id": "packing-3",
   "title": "Deep tapped hole: chips stick, torque rises",
   "fix": "Use Fanuc peck rigid tapping: add Q (depth per peck) to the G84 line.",
   "src": {
    "name": "Fanuc 30i-A manual p.85",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "packing-4",
   "title": "Outside coolant on a deep or long-chipping tapped hole",
   "fix": "Use through-tool coolant, preferred for long-chipping materials and holes over 2-3 x D.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/threading/tapping/operation-tips"
   }
  },
  {
   "id": "packing-5",
   "title": "Drill chips too long and not breaking",
   "fix": "Peck (step feed) or raise feed to break chips. G73 breaks chips; G83 fully retracts.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319429/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Drilling-_Vol_1_-_IA.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/choosing-the-right-pecking-cycle-approach/"
    }
   ]
  },
  {
   "id": "packing-6",
   "title": "Deep drilled hole without through-coolant",
   "fix": "Use internal coolant for holes deeper than 3 x D, especially long-chipping materials.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-tips"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/selecting-the-right-harvey-tool-miniature-drill/"
    }
   ]
  },
  {
   "id": "packing-7",
   "title": "Low coolant flow or clogged coolant holes",
   "fix": "Increase coolant flow, clean the filter, and clear the drill's coolant holes. Put a 5 µm prefilter on through-spindle coolant.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-wear-and-troubleshooting"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://harveyperformance.widen.net/content/icmzdcl9s5/pdf/SF_CXZ0000.pdf"
    }
   ]
  },
  {
   "id": "packing-8",
   "title": "Drill flute can't carry the chip",
   "fix": "Pick a wide-flute, high-helix or oil-hole drill, or switch to step drilling.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319429/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Drilling-_Vol_1_-_IA.pdf"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/choosing-the-right-pecking-cycle-approach/"
    }
   ]
  }
 ],
 "burn": [
  {
   "id": "burn-1",
   "title": "Cutting speed too high",
   "fix": "Lower the speed. Too much speed gives rapid flank and corner wear.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-tips"
   }
  },
  {
   "id": "burn-2",
   "title": "Feed too high",
   "fix": "Lower the feed. High feed raises the risk of drill breakage.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-tips"
   }
  },
  {
   "id": "burn-3",
   "title": "Feed too low: rubbing and fast wear",
   "fix": "Raise the feed into the recommended range. In titanium and nickel alloys, raise feed if work hardening shows.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-tips"
   }
  },
  {
   "id": "burn-4",
   "title": "Not enough coolant, or oil mix too lean",
   "fix": "Raise coolant flow. Keep emulsion 5-12% oil (10-15% for stainless and heat-resistant alloys).",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-tips"
   }
  },
  {
   "id": "burn-5",
   "title": "Too much runout",
   "fix": "Check radial runout; it causes margin wear, chipping and breakage.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-wear-and-troubleshooting"
   },
   "also": [
    {
     "name": "Harvey Tool",
     "url": "https://www.harveyperformance.com/in-the-loupe/reducing-tool-runout/"
    }
   ]
  },
  {
   "id": "burn-6",
   "title": "Chips jamming in the flutes",
   "fix": "Check coolant supply, and peck or change feed so the chips break.",
   "src": {
    "name": "Sandvik Coromant",
    "url": "https://www.sandvik.coromant.com/en-us/knowledge/drilling/drilling-wear-and-troubleshooting"
   }
  },
  {
   "id": "burn-7",
   "title": "Drill material wrong for the work hardness",
   "fix": "Choose a suitable tool material, such as carbide for hard steel.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319429/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Drilling-_Vol_1_-_IA.pdf"
   }
  },
  {
   "id": "burn-8",
   "title": "Drill run past its wear limit",
   "fix": "Regrind or replace sooner. Don't exceed max wear before regrinding carbide.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319429/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Drilling-_Vol_1_-_IA.pdf"
   }
  }
 ],
 "finish": [
  {
   "id": "finish-1",
   "title": "Galling: chips welding to the tap flanks",
   "fix": "Use thread-relieved, surface-treated taps, proper lubricant and lower speed.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "finish-2",
   "title": "Wrong lubricant or coolant mix too lean",
   "fix": "Change coolant method or raise volume and concentration. Check the mix with a refractometer.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319427/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Tap_-_Vol_1_-_IA.pdf"
   }
  },
  {
   "id": "finish-3",
   "title": "Chip packing tearing the threads",
   "fix": "Use spiral point or spiral flute taps and a larger drill.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "finish-4",
   "title": "Chamfer too short (bottoming tap)",
   "fix": "Use a longer chamfer, like a plug tap, when the hole depth allows.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "finish-5",
   "title": "Tap retracting too fast",
   "fix": "Lower retract speed if threads tear. Haas: Setting 130. Fanuc: extraction override, parameter 5211.",
   "src": {
    "name": "Haas Automation",
    "url": "https://www.haascnc.com/service/troubleshooting-and-how-to/troubleshooting/tap-breakage-troubleshooting.html"
   }
  },
  {
   "id": "finish-6",
   "title": "Tapping speed too high",
   "fix": "Reduce the tapping speed.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  },
  {
   "id": "finish-7",
   "title": "Floating holder on a full-sync machine",
   "fix": "On a fully synchronized machine use a rigid holder; imperfect sync tears threads and leaves burrs.",
   "src": {
    "name": "OSG USA",
    "url": "https://res.cloudinary.com/osg-usa-inc/image/upload/v1709319427/Literature/03%20-%20Charts%20and%20Guides/Technical%20Guides/OSG_-_Literature_-_Other_-_Technical_Data_-_Tap_-_Vol_1_-_IA.pdf"
   }
  },
  {
   "id": "finish-8",
   "title": "Tap not lined up with the hole",
   "fix": "Get the tap and the workpiece properly aligned.",
   "src": {
    "name": "YG-1",
    "url": "https://www.suncoasttools.com/PDFFILES/YG1/Technical/Taps/YG1-TAP-TROUBLE-SHOOTING-GUIDE.pdf"
   }
  }
 ],
 "fanuc": [
  {
   "id": "fanuc-1",
   "title": "F doesn't equal RPM x lead",
   "fix": "G94: F = S x lead. G95: F = lead. If F is rounded, use G95.",
   "src": {
    "name": "Fanuc 30i-A manual p.78",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "fanuc-2",
   "title": "S word or move between M29 and G84",
   "fix": "Put M29 S__ on its own line right before G84. Otherwise alarm PS0203.",
   "src": {
    "name": "Fanuc 30i-A manual p.80",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "fanuc-3",
   "title": "No M29, so G84 runs as ordinary float tapping",
   "fix": "Add M29 S__ before G84, or confirm parameter 5200#0 makes G84 rigid-only.",
   "src": {
    "name": "Fanuc 16i-B manual p.1126",
    "url": "https://www.drivesul.com.br/template/imagens/manuais/manuais-fanuc/fanuc-series-16i-18i-21i-model-b/Series%2016i-18i-21i-MODEL%20B%20-%20Connection%20Manual%20(Function).pdf#page=1154"
   }
  },
  {
   "id": "fanuc-4",
   "title": "Expecting the override knobs to work in G84",
   "fix": "Overrides are held at 100% while rigid tapping. Change S and F in the program.",
   "src": {
    "name": "Fanuc 30i-A manual p.77",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "fanuc-5",
   "title": "Extraction override makes the retract faster than the feed-in",
   "fix": "Check 5200#4 (DOV), 5211 and any J word. Haas advises a slower retract if threads tear.",
   "src": {
    "name": "Fanuc 30i-A manual p.90",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "fanuc-6",
   "title": "Deep hole: chips stick and cutting load rises",
   "fix": "Use peck rigid tapping: Q = depth per peck, Q0 = no peck. 5200#5 (PCP) sets the type.",
   "src": {
    "name": "Fanuc 30i-A manual p.85",
    "url": "https://manualmachine.com/fanuc/30ia/4715028-user-manual/"
   }
  },
  {
   "id": "fanuc-7",
   "title": "Tension/compression holder used for M29 rigid tapping",
   "fix": "Use a rigid or Softsynchro-type minimal-compensation holder. Full float can overcut on synchronized spindles.",
   "src": {
    "name": "OSG",
    "url": "https://www.mscdirect.com/knowledge-center/articles/video-60sec-troubleshooting-threading-tension-compression-vs-rigid-tapping"
   }
  },
  {
   "id": "fanuc-8",
   "title": "Spindle and Z sync error during tapping",
   "fix": "Watch diagnostics 455-457 while tapping. Parameter 5214 sets the alarm 741 limit. Have service tune it.",
   "src": {
    "name": "Fanuc 16i-B manual p.1134",
    "url": "https://www.drivesul.com.br/template/imagens/manuais/manuais-fanuc/fanuc-series-16i-18i-21i-model-b/Series%2016i-18i-21i-MODEL%20B%20-%20Connection%20Manual%20(Function).pdf#page=1162"
   }
  }
 ]
}; })();
